import type { LucideIcon } from "lucide-react"
import {
  Utensils,
  Car,
  ShoppingBag,
  Film,
  Receipt,
  Heart,
  Banknote,
  Briefcase,
  TrendingUp,
  Circle,
  Coffee,
  Home,
  Plane,
  Music,
  Book,
  Gift,
  Phone,
  Zap,
  Droplets,
  Wifi,
  Bus,
  Train,
  Bike,
  ShoppingCart,
  Gamepad2,
  Shirt,
  Scissors,
  Dog,
  Baby,
  GraduationCap,
  Pill,
  Dumbbell,
} from "lucide-react"

const ICON_MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  car: Car,
  "shopping-bag": ShoppingBag,
  film: Film,
  receipt: Receipt,
  heart: Heart,
  banknote: Banknote,
  briefcase: Briefcase,
  "trending-up": TrendingUp,
  coffee: Coffee,
  home: Home,
  plane: Plane,
  music: Music,
  book: Book,
  gift: Gift,
  phone: Phone,
  zap: Zap,
  droplets: Droplets,
  wifi: Wifi,
  bus: Bus,
  train: Train,
  bike: Bike,
  "shopping-cart": ShoppingCart,
  gamepad2: Gamepad2,
  shirt: Shirt,
  scissors: Scissors,
  dog: Dog,
  baby: Baby,
  "graduation-cap": GraduationCap,
  pill: Pill,
  dumbbell: Dumbbell,
}

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Circle
}
